// <auto-generated />
using System;
using CrowDo1st;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CrowDo1st.Migrations
{
    [DbContext(typeof(CrowDoDbContext))]
    partial class CrowDoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CrowDo1st.Package", b =>
                {
                    b.Property<int>("PackageId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<decimal>("LowerBound");

                    b.Property<int?>("ProjectId");

                    b.Property<string>("Reward");

                    b.Property<string>("Title");

                    b.HasKey("PackageId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Package");
                });

            modelBuilder.Entity("CrowDo1st.Photos", b =>
                {
                    b.Property<int>("PhotoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int?>("ProjectProfilePageProjectId");

                    b.HasKey("PhotoId");

                    b.HasIndex("ProjectProfilePageProjectId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("CrowDo1st.ProjectProfilePage", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<decimal>("Balance");

                    b.Property<int>("Category");

                    b.Property<DateTime>("DateOfCreation");

                    b.Property<DateTime>("DeadLine");

                    b.Property<string>("Description");

                    b.Property<int>("TimeScope");

                    b.Property<string>("Title");

                    b.Property<int?>("UserId");

                    b.HasKey("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectProfilePage");
                });

            modelBuilder.Entity("CrowDo1st.Updates", b =>
                {
                    b.Property<int>("UpdatesId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfUpdate");

                    b.Property<string>("DescriptionOfUpdate");

                    b.Property<int?>("ProjectProfilePageProjectId");

                    b.Property<string>("Title");

                    b.HasKey("UpdatesId");

                    b.HasIndex("ProjectProfilePageProjectId");

                    b.ToTable("Updates");
                });

            modelBuilder.Entity("CrowDo1st.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CardNumber")
                        .HasColumnName("Card number");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnName("Date of birth");

                    b.Property<DateTime>("DateOfRegister")
                        .HasColumnName("Date of registration");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Location");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CrowDo1st.UserProject", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<int>("ProjectId");

                    b.HasKey("UserId", "ProjectId");

                    b.HasIndex("ProjectId");

                    b.ToTable("FundedProjects");
                });

            modelBuilder.Entity("CrowDo1st.Videos", b =>
                {
                    b.Property<int>("VideoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int?>("ProjectProfilePageProjectId");

                    b.HasKey("VideoId");

                    b.HasIndex("ProjectProfilePageProjectId");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("CrowDo1st.Package", b =>
                {
                    b.HasOne("CrowDo1st.ProjectProfilePage", "Project")
                        .WithMany("Packages")
                        .HasForeignKey("ProjectId");
                });

            modelBuilder.Entity("CrowDo1st.Photos", b =>
                {
                    b.HasOne("CrowDo1st.ProjectProfilePage")
                        .WithMany("Photos")
                        .HasForeignKey("ProjectProfilePageProjectId");
                });

            modelBuilder.Entity("CrowDo1st.ProjectProfilePage", b =>
                {
                    b.HasOne("CrowDo1st.User", "User")
                        .WithMany("CreatedProjects")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("CrowDo1st.Updates", b =>
                {
                    b.HasOne("CrowDo1st.ProjectProfilePage")
                        .WithMany("Update")
                        .HasForeignKey("ProjectProfilePageProjectId");
                });

            modelBuilder.Entity("CrowDo1st.UserProject", b =>
                {
                    b.HasOne("CrowDo1st.ProjectProfilePage", "ProjectProfilePage")
                        .WithMany("UserProject")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CrowDo1st.User")
                        .WithMany("UserProject")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CrowDo1st.Videos", b =>
                {
                    b.HasOne("CrowDo1st.ProjectProfilePage")
                        .WithMany("Videos")
                        .HasForeignKey("ProjectProfilePageProjectId");
                });
#pragma warning restore 612, 618
        }
    }
}
